export type CarrierProfileExtras = {
  accountType?: string | null;
  companyName?: string | null;
  contactPerson?: string | null;
  address?: string | null;
  addressLine1?: string | null;
  addressLine2?: string | null;
  city?: string | null;
  postcode?: string | null;
  countryName?: string | null;
  operatorId?: string | null;
  registrationNo?: string | null;
  nationalId?: string | null;
  insuranceExpiry?: string | null;
  primaryVehicle?: string | null;
  vehicleTypes?: string | string[] | null;
  fleetSize?: string | null;
  operatingRegion?: string | string[] | null;
  availability?: string | null;
  directoryListing?: boolean | null;
  maxCapacityKg?: string | null;
  countryCode?: string | null;
  phone?: string | null;
  alternatePhone?: string | null;
  email?: string | null;
  website?: string | null;
  companyType?: string | null;
  yearsInBusiness?: string | null;
  description?: string | null;
  servicesOffered?: string[] | null;
  specializations?: string[] | null;
  logoUrl?: string | null;
  verificationStatus?: string | null;
  verificationNotes?: string | null;
  verifiedBy?: string | null;
  verifiedDate?: string | null;
  insuranceCertificateUrl?: string | null;
  operatorLicenseUrl?: string | null;
  vehicleRegistrationUrl?: string | null;
  backgroundCheckUrl?: string | null;
  accountStatus?: string | null;
  preferredPaymentMethod?: string | null;
  payoutMethod?: string | null;
  payoutSetupComplete?: boolean | null;
  bankAccountHolderName?: string | null;
  bankName?: string | null;
  bankCountry?: string | null;
  bankSortCode?: string | null;
  bankAccountNumber?: string | null;
  bankAccountType?: string | null;
  bankRecipientNickname?: string | null;
  bankRecipientBirthYear?: string | null;
  addToTrustedBeneficiaries?: boolean | null;
  paymentTerms?: string | null;
  internalNotes?: string | null;
  avatarUrl?: string | null;
  bannerUrl?: string | null;
};

export type SupplierProfileExtras = {
  accountType?: string | null;
  companyName?: string | null;
  contactPerson?: string | null;
  address?: string | null;
  city?: string | null;
  registrationNo?: string | null;
  taxId?: string | null;
  industry?: string | null;
  monthlyVolume?: string | null;
  commodity?: string | null;
  averageWeight?: string | null;
  averageValue?: string | null;
  invoicingEmail?: string | null;
  countryCode?: string | null;
  phone?: string | null;
  email?: string | null;
  avatarUrl?: string | null;
  bannerUrl?: string | null;
};

export const getCarrierExtrasKey = (userId: string) => `carrier-profile-extras:${userId}`;
export const getSupplierExtrasKey = (userId: string) => `supplier-profile-extras:${userId}`;
